#spring.application.name=AmsSpringBoot
#server.port=8080
#spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
#spring.datasource.url=jdbc:derby:C:\Users\Admin\AMS_Angular_and_Spring;create=true


spring.application.name=AmsSpringBoot
server.port=${PORT:8080}
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.datasource.url=jdbc:derby:./ams_db;create=true